#spring.application.name=identify-service
server:
    port: 8080
    servlet:
        context-path: /identify

spring:
    datasource:
        url: jdbc:mysql://localhost:3307/identify_service
        username: root
        password: admin123

